### PR TITLE
Add undocumented measurement types, support for segmented values

### PR DESCRIPTION
**Pull request by anthonym21**
# Proposed Changes

Add models for Position (for segmented measurements) and add on to Measurement some of the undocumented types that are causing errors in Home Assistant component

Ignore the changes I had to make to get some of the tests through, I'm not a python dev.

# Note

I am not typically a github user and I don't really code in Python but I do use this package and I have a Body Scan and I just wanted to add in measurement types that are showing up as errors in the Home Assistant component.  I don't care if you use the PR, but if you want to cherry pick out the values I added to the Measurement and add Position that are missing I just want the component to work without errors again.  I attached a sample API get_measurement response which includes the fields so you can see what they look like.
[withings.json](https://github.com/joostlek/python-withings/files/14076860/withings.json)

I was going to also PR the home assistant component to add some new sensors around this and add support for position, which I did do, but I had enough trouble getting through the python linters and testing on this project with no experience, forget the ones on the HA project, it took me way too long just to add a few enum values so I will leave that as an exercise to an actual Python dev.

## Related Issues

> #157 
> #145 
> #138

### CODE REVIEW

**Comment by joostlek** [comment]
Oh lol, I saw your fork but I didn't see this PR. This is quite nice since I am missing this info and was trying to get to know it via users.

I think I will cherry pick the info from the PR to implement (since you said you don't mind) since there are also some things that I might implement differently.

I am wondering, when you check your measurements, do you see all positions in every measurement? Or do you sometimes have a measurement with only the left side of the body (as example)?

**Comment by anthonym21** [comment]
Yes I am sure you would implement them differently as I don't really know what I'm doing in Python, lol, I just did not know how to submit the information without a PR to show it.  So go right ahead with that.

If I get segmented measurements, I always get all of them, but there are really only 10 I see in the app there are 5 segmented fat % (R/L arm, Torso, R/L leg) 5 segmented muscle mass (same group) -- I am not sure why you get fat in %, but it cannot be toggled like other fat ratio display.  I see some additional breakdown of segments and/or left/right in the API results, but they're not in the app, electro derma readings from the feet for instance seem to be measured per foot but I had no idea and honestly I don't even know what the measurement is to begin with.

I also notice a lot of non-segmented measurements in the API return a position = 7 which I have attributed to "Whole Body" or "Non Segmented" as I do not believe it was officially called out anywhere.  The 7 is likely the default value, although it was frustrating trying to figure out how to implement the model with the position property potentially optional, because there are measurements which lack it entirely.

**Comment by joostlek** [comment]
I'll be looking into it this week, if we're lucky we might even finish it before Wednesday so we can do some changes in HA for 2024.2, otherwise it will be 2024.3

**Comment by anthonym21** [comment]
Not meant to be merged for information only

**Comment by joostlek** [comment]
Haven't found the time yet as I am also busy trying to graduate :)

**Comment by anthonym21** [comment]
It's all good man, i work at DraftKings it's Superbowl weekend so i have
been living the vida loca myself

**Pull request closed without merging**
